
version: 2

models:
  - name: int_users
    description: "On this table performs some test to ensure data quality."
    columns:
      - name: age
        description: "Age should be greater than 0 "
        tests:
          - greater_than_zero
      - name: gender
        description: "It accepts only Male, Female and Unknown."
        tests:
          - accepted_values:
              values: ['Male', 'Female', 'Unknown']

  - name: int_products
    description: "On this table performs tests on prod_cost, prod_retail_price and prod_sku"
    columns:
      - name: prod_cost
        description: "Cost should be greater than zero."
        tests:
          - greater_than_zero
      - name: prod_retail_price
        description: "It should be greater than zero."
        tests:
          - greater_than_zero
      - name: prod_sku
        description: "It should be unique for each product."
        tests:
          - unique
  
  - name: int_orders
    description: "In this table performs tests on status and num_of_item columns."
    columns:
      - name: status
        description: "It accepts only Cancelled, Complete, Processing, Returned, Shipped."
        tests:
          - accepted_values:
              values: ['Cancelled', 'Complete', 'Processing', 'Returned','Shipped']
      - name: num_of_item
        description: "It should be greater than 0."
        tests:
          - greater_than_zero

  - name: int_inventory
    description: "In this table performs tests on cost, prod_retail_price and prod_sku."
    columns:
      - name: cost
        description: "It should be greater than 0."
        tests:
          - greater_than_zero
      - name: prod_retail_price
        description: "It also should be greater than zero."
        tests:
          - greater_than_zero
  
  - name: int_events
    description: "In this table performs tests on several columns such as sequence_num, ip_address, browser, traffic_source, uri, event_type."
    columns:
      - name: sequence_num
        description: "It should be greater than 0"
        tests:
          - greater_than_zero
      - name: browser
        description: "it accepts only Firefox, Other, IE, Chrome, Safari."
        tests:
          - accepted_values:
              values: ['Firefox', 'IE', 'Chrome', 'Safari', 'Other']
      - name: traffic_source
        description: "It accepts only Adwords, Facebook, Email, Organic, Youtube."
        tests:
          - accepted_values:
              values: ['Adwords','Facebook','Email','Organic','YouTube']
      - name: event_type
        description: "It accepts only cancel, cart, department, home, product, purchase."
        tests:
          - accepted_values:
              values: ['cancel','cart','department','home','product','purchase']
        
  - name: int_order_items
    description: "In this table performs tests on status, sale_price column."
    columns:
      - name: status
        description: "It accepts only Cancelled, Compete, Processing, Returned, Shipped."
        tests:
          - accepted_values:
              values: ['Cancelled', 'Complete', 'Processing', 'Returned', 'Shipped']
      - name: sale_price
        description: "It should not be less than zero."
        tests:
          - greater_than_zero