
version: 2

models:
  - name: stg_distributions
    description: "This table contains distributors information"
    columns:
      - name: dist_id
        description: "This is a primary key for this table."
        tests:
          - not_null
          - unique
      - name: dist_name
        description: " Name of the distribution center."
      - name: latitude
        description: " Latitude coordinate of the distribution center."
      - name: longitude
        description: "Longitude coordinate of the distribution center."

  - name: stg_events
    description: "This table contains all information of events."
    columns:
      - name: event_id
        description: "This is a primary key for this table."
        tests:
          - not_null
          - unique
      - name: user_id
        description: " Identifier for the user associated with the event."
      - name: sequence_num
        description: "Sequence number of the event."
      - name: session_id
        description: " Identifier for the session during which the event occurred."
      - name: created_at
        description: " Timestamp indicating when the event took place."
      - name: ip_address
        description: " IP address from which the event originated."
      - name: browser
        description: "Web browser used during the event."
      - name: traffic_source
        description: "Source of the traffic leading to the event."
      - name: uri
        description: "Uniform Resource identifier associated with the event."
      - name: event_type
        description: "Type of event recorded."

  - name: stg_inventory
    description: "This table contains all information of inventory."
    columns:
      - name: inventory_id
        description: "This is a primary key for this table."
        tests:
          - not_null
          - unique
      - name: prod_id
        description: " Identifier for the user associated product."
      - name: sold_at
        description: "Timestamp indicating when the item was sold."
      - name: cost
        description: "Cost of the inventory item."
      - name: prod_retial_price
        description: "Retail price of the associated product."
      - name: prod_sku
        description: "Stock Keeping Unit (SKU) of the product."
      
  - name: stg_order_items
    description: "This table contains all information of order's items."
    columns:
      - name: order_item_id
        description: "This is a primary key for this table."
        tests:
          - not_null
          - unique
      - name: status
        description: " Status of the order item."
      - name: sale_price
        description: "selling price for each item."

  - name: stg_orders
    description: "This table contains all information of orders."
    columns:
      - name: order_id
        description: "This is a primary key for this table."
        tests:
          - not_null
          - unique
      - name: status
        description: " Status of the order."
      - name: num_of_item
        description: "Number of items in the order."
  
  - name: stg_products
    description: "This table contains all information of products."
    columns:
      - name: prod_id
        description: "This is a primary key for this table."
        tests:
          - not_null
          - unique
      - name: cost
        description: "Cost of the product."
      - name: name
        description: "Name of the product."
      - name: prod_category
        description: "Category to which the product belongs."
      - name: brand
        description: "Brand of the product."
      - name: retail_price
        description: "Retail price of the product."
      - name: department
        description: "Department to which the product belongs."
      - name: sku
        description: "Stock keeping unit(SKU) of the product."
  
  - name: stg_products
    description: "This table contains all information of products."
    columns:
      - name: prod_id
        description: "This is a primary key for this table."
        tests:
          - not_null
          - unique
      - name: cost
        description: "Cost of the product."
      - name: name
        description: "Name of the product."
      - name: prod_category
        description: "Category to which the product belongs."
      - name: brand
        description: "Brand of the product."
      - name: retail_price
        description: "Retail price of the product."
      - name: department
        description: "Department to which the product belongs."
      - name: sku
        description: "Stock keeping unit(SKU) of the product."
  
  - name: stg_users
    description: "This table contains all information of users."
    columns:
      - name: user_id
        description: "This is a primary key for this table."
        tests:
          - not_null
          - unique
      - name: traffic_source
        description: " Source of the traffic leading to the user."
      